In [2]:
import numpy as np
from typing import Any

from cat_record import CatRecord

In [3]:
def output_info(np_array: np.ndarray):
    print(f"Shape: {np_array.shape}")
    print(f"NDim: {np_array.ndim}")
    print(f"DType: {np_array.dtype}")
    print(f"Size: {np_array.size}")
    print(f"Content:\n{np_array}")

In [4]:
a = np.array([1,2,3,4,5,6])
output_info(a)

Shape: (6,)
NDim: 1
DType: int64
Size: 6
Content:
[1 2 3 4 5 6]


In [5]:
b = np.array(10)
output_info(b)

Shape: ()
NDim: 0
DType: int64
Size: 1
Content:
10


In [6]:
class StudentRecots:
    def __init__(self, name, age: int):
        self.name = name
        self.age = age
    def __str__(self):
        return f"{self.name} ({self.age})"

In [7]:
sr = StudentRecots("Emilio", 5)
print(sr)

Emilio (5)


In [8]:
c = CatRecord("Davids Katze", 2)
print(c)

Davids Katze (2)


In [9]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
output_info(matrix)
matrix

Shape: (3, 3)
NDim: 2
DType: int64
Size: 9
Content:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
output_info(np.arange(2,10,5))

Shape: (2,)
NDim: 1
DType: int64
Size: 2
Content:
[2 7]


In [11]:
output_info(np.zeros([2,3]))


Shape: (2, 3)
NDim: 2
DType: float64
Size: 6
Content:
[[0. 0. 0.]
 [0. 0. 0.]]


In [12]:
output_info(np.zeros([2,3]).reshape(6))

Shape: (6,)
NDim: 1
DType: float64
Size: 6
Content:
[0. 0. 0. 0. 0. 0.]


In [13]:
 a = np.arange(0,4)
 a.reshape(2,2)

array([[0, 1],
       [2, 3]])

In [14]:
mx = np.arange(1,13).reshape(3,4)
output_info(mx)
mx[:,:2]

Shape: (3, 4)
NDim: 2
DType: int64
Size: 12
Content:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]])

In [15]:
print(mx == 6)
print(mx < 9)
print(mx[mx < 9])
mx[mx>10] = 100
print(mx)

[[False False False False]
 [False  True False False]
 [False False False False]]
[[ True  True  True  True]
 [ True  True  True  True]
 [False False False False]]
[1 2 3 4 5 6 7 8]
[[  1   2   3   4]
 [  5   6   7   8]
 [  9  10 100 100]]


In [16]:
y = [2,3,4,5,6]
y2 = y[:3]
y[0] = 99
print(y2)

[2, 3, 4]


In [17]:
y = np.array([2,3,4,5,6])
y2 = y[:3]
y[0] = 99
print(y2)

[99  3  4]
