## Numpy Übungen

Importiere hier alle benötigten Python Packages
* Numpy (mit dem Aliasnamen **np**)

In [1]:
import numpy as np
import traceback # für später

gebe für alle importieren Pakages die verwendete Versionummer aus.

Dazu musst du herausfinden wie die Version eines Python Packages ausgelesen werden kann.

In [2]:
print(np.__version__)

2.2.6


* Erzeuge einen Vektor!!! mit der Länge 5 und den Werten 1,2,3,4,5

In [3]:
vec = np.array(range(1,6))
vec

array([1, 2, 3, 4, 5])

Erzeuge folgende Matrizen

* 3x3 mit den Werten 1-9
* 4x6 mit den Werten 10,20,30,....
* 3x7 mit Werten im Bereich von 10-20. Die einzelnen Werte zueinander sollen dabei den gleichen Abstand haben.

In [4]:
m3x3 = np.arange(1,10).reshape([3,3])
m3x3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
m4x6 = np.arange(10,241,10).reshape([4,6])
m4x6

array([[ 10,  20,  30,  40,  50,  60],
       [ 70,  80,  90, 100, 110, 120],
       [130, 140, 150, 160, 170, 180],
       [190, 200, 210, 220, 230, 240]])

In [6]:
m3x7 = np.linspace(10,20, 21).reshape([3,7])
m3x7

array([[10. , 10.5, 11. , 11.5, 12. , 12.5, 13. ],
       [13.5, 14. , 14.5, 15. , 15.5, 16. , 16.5],
       [17. , 17.5, 18. , 18.5, 19. , 19.5, 20. ]])

Erzeuge eine Matrix 'v' (5x5) welche mit Zufallszahlen befüllt ist.
Die Zufallszahlen sollen dabei "Normalverteilt" sein.
Suche dazu die passende Funktion in der **numpy** Dokumentation.

In [7]:
v = np.random.normal(size=25).reshape([5,5])
v

array([[ 0.1521127 ,  1.54686607,  2.63483224,  0.70185597,  0.10108394],
       [-2.44221374,  1.2263152 , -0.83660431, -0.95936341,  0.86277784],
       [ 1.0597918 ,  0.81568291,  1.29508042, -0.81671036,  1.23247408],
       [ 0.64798876,  0.42948787, -0.35710627,  0.57604337,  0.28659211],
       [-1.0076481 ,  0.85269448,  2.19272632,  2.02346646, -0.62640837]])

Erzeuge eine Matrix 'v' (3x4) welche mit Zufallszahlen befüllt ist.
Die Zufallszahlen sollen dabei "Gleichverteilt" sein im Bereich von 20-30 sein
Suche dazu die passende Funktion in der **numpy** Dokumentation.

In [8]:
v = np.random.uniform(low=20,high=30,size=12).reshape([3,4])
v

array([[22.80604092, 21.39978849, 25.92997665, 27.69498565],
       [23.00754277, 25.43912453, 24.87661583, 26.39661301],
       [23.95640529, 22.7742232 , 27.02858894, 20.34419362]])

Erzeuge eine Matrix 'v' (2x5) welche mit Integer-Zufallszahlen befüllt ist.
Die Zufallszahlen sollen dabei "Gleichverteilt" sein im Bereich von 0-255 und mit dem Datentyp '**uint8**' abgespeichert werden.
Suche dazu die passende Funktion in der **numpy** Dokumentation.


In [9]:
v = np.random.randint(low=0,high=255, size=(2,5), dtype="uint8")
v

array([[110,  70, 134, 152, 222],
       [ 54, 167,  82, 233, 154]], dtype=uint8)

Erzeuge eine Matrix (3x3) welche aus lauter Nullen besteht und eine 2. Matrix welche aus lauter Einsen besteht.

Verwende zum Erzeugen der Matrix die passende numpy Funktion.

In [10]:
m3x3z = np.zeros((3,3))
m3x3z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [11]:
m3x3o = np.ones((3,3))
m3x3o

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

Erzeuge eine Matrix (4,4) welche in der Hauptdiagonale lauter Einser besitzt, alle anderen Elemente sollen Null sein.<br>
Eine Matrix welche in der Hauptdiagonale nur Einser besitzt und ansonsten lauter Nullen wird auch als **Einheitsmatrix** bezeichnet.

Verwende zum Erzeugen der Matrix die passende numpy Funktion.

In [12]:
m4identity = np.identity(4)
m4identity

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

Erzeuge eine Matrix M (3x3) mit Integer Zufallszahlen im Bereich (10,20] und Einheitsmatrix E, ebenfalls 3x3.<br>
Multipliziere (Matrixmultiplikation) die Matrix M mit der Einheitsmatrix E.
Wie lautet das Ergebnis der Berechnung und wie unterscheidet sich das Erbebnis von der ursprünglichen Matrix M?
$$
X = M * E
$$

In [13]:
M = np.random.randint(10,20, size=(3,3))
E = np.identity(3)
X = M * E

# Alles ist 0 wo E 0 ist
X

array([[11.,  0.,  0.],
       [ 0., 12.,  0.],
       [ 0.,  0., 14.]])

## Übungen zum Indizieren und Teilbereichsoperator

Erzeuge eine Matrix M (4x4) mit den Zahlen 1...16 welche für die nachfolgenden Übungen verwendet werden soll.<br>
Erzeuge auch einen Vektor V mit der Länge 10 und den Zahlen 2,4,6,8,......

In [14]:
M = np.arange(1, 17).reshape((4,4))
V = np.arange(2,21,2)

- Selektiere das 1. Element des Vektors V
- Selektiere die ersten 3 Elemente des Vektors V
- Seletiere alle ungeraden Elemente des Vektors V
- Selektiere das erste, fünfte und letzte Element des Vektors V

In [15]:
V[0]

np.int64(2)

In [16]:
V[:3]

array([2, 4, 6])

In [17]:
V[V % 2 == 1]

array([], dtype=int64)

In [18]:
V[[0,4,-1]]

array([ 2, 10, 20])

- Selektiere die erste Zeile der Matrix M
- Selektiere die erste Spalte der Matrix M
- Selektiere die ersten 3 Zeilen der Matrix M
- Selektiere die ersten 3 Spalten der Matrix M
- Selektiere die letzte Spalte der Matrix M
- Selektiere aus den Zeilen 1 und 2, die Spalten 3 und 4. Damit ergibt  sich eine neue 4x4 Matrix

In [19]:
M[0,:]

array([1, 2, 3, 4])

In [20]:
M[:,0]

array([ 1,  5,  9, 13])

In [21]:
M[:3,:]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [22]:
M[:,:3]

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15]])

In [23]:
M[:,-1]

array([ 4,  8, 12, 16])

In [24]:
M[:2,2:4]

array([[3, 4],
       [7, 8]])

Erzeuge eine Matrix M (5x4) mit zufälligen Integerwerten 0-300 und dem Datentyp uint16<br>

- Maskiere alle Werte der Matrix M welche größer als 255 sind und sezte diese auf den Wert 255. Speichere das Ergebnis in einer neuen Matrix mit dem Datentyp **uint8**. Schaue in der Doku mach mit welchem Befehl sich der Datentyp ändern läßt.

- Gib alle Elemente der Matrix M aus deren Wert eine 'gerade' Zahl ist.


In [25]:
M = np.random.randint(low=0, high=300, dtype="uint16", size=(5,4))
M

array([[ 90, 212, 138, 277],
       [ 39, 260,  27, 146],
       [143, 215, 228, 209],
       [115, 290,  56, 172],
       [ 97, 260, 178,  14]], dtype=uint16)

In [26]:
M2 = M.copy()
M2[M2 > 255] = 255
M2 = M2.astype("uint8")
M2

array([[ 90, 212, 138, 255],
       [ 39, 255,  27, 146],
       [143, 215, 228, 209],
       [115, 255,  56, 172],
       [ 97, 255, 178,  14]], dtype=uint8)

In [27]:
M[M % 2 == 0]

array([ 90, 212, 138, 260, 146, 228, 290,  56, 172, 260, 178,  14],
      dtype=uint16)

Erzeuge ein 2.Dim Python-Array!!! mit den Werte 1,2,3,4 in der 1. Zeile und <br>
5,6,7,8 in der 2. Zeile. Wandle dieses Array in ein numpy Array (Matrix M) um und gib dessen Shape aus.

- Erzeuge aus der Matrix M eine neue Matrix M2 (8x2)
- Erzeuge aus der Matrix M einen Vektor V. Entsprechende Funktion aus der Dokumentation raussuchen und anwenden. Wie viele Elemente enthält der entstandene Vektor?

In [28]:
#arr = [[1,2,3,4], [5,6,7,8]]
arr = [[b for b in range(a*4+1, (a+1)*4+1)] for a in range(2)]
M = np.array(arr)
M.shape

(2, 4)

In [29]:
try:
    M2 = M.reshape((8,2)) # kann nicht funktionieren, da M.size 16 ist
except ValueError as e:
    print(traceback.format_exc())

Traceback (most recent call last):
  File "/tmp/ipykernel_21449/4234647282.py", line 2, in <module>
    M2 = M.reshape((8,2)) # kann nicht funktionieren, da M.size 16 ist
ValueError: cannot reshape array of size 8 into shape (8,2)



In [30]:
V = M.flatten()
V # Antwort: 8 Elemente

array([1, 2, 3, 4, 5, 6, 7, 8])

Erzeuge 2 Matrizen M, N . Beide sollen die Dimension 2x2 haben und mit zufälligen Integerwerten befüllt sein.

- Erzeuge eine neue Matrix X indem die beiden Matrizen M, N horizontal aneinandergefügt werden. Gib die Werte der Matrix X sowie die Shape aus
- Erzeuge eine neue Matrix X indem die beiden Matrizen M, N vertikal aneinandergefügt werden. Gib die Werte der Matrix X sowie die Shape aus

In [31]:
M,N = [np.random.randint(low=0, high=255,size=(2,2)) for _ in range(2)]

In [32]:
X = np.hstack((M,N))
print(X.shape)
X

(2, 4)


array([[  7, 246,  86,   0],
       [218, 227,  70,  50]])

In [33]:
X = np.vstack((M,N))
print(X.shape)
X

(4, 2)


array([[  7, 246],
       [218, 227],
       [ 86,   0],
       [ 70,  50]])

## Numerische und Statistik Operationen auf Numpy Arrays

Erzeuge 2 Matrizen M, N . Beide sollen die Dimension 4x4 haben und mit zufälligen Integerwerten(0...20) befüllt sein.

- Addiere die beiden Matrizen
- Subtrahiere die beiden Matrizen
- Multiplizieren die beiden Matrizen
- Dividiere die beiden Matrizen. Sollten in der 2. Matrix an bestimmten Stellen nullen vorkommen, so sind diese vor der Divison durch eine 1 zu ersetzen (wegen Division durch 0)

- Multipliziere die Matrix M mit dem Skalarwert 5


In [34]:
M,N = [np.random.randint(low=0, high=20,size=(4,4)) for _ in range(2)]

In [35]:
M + N

array([[15, 18, 31,  3],
       [17, 18, 25, 13],
       [32, 26, 26, 12],
       [ 9,  9, 20, 16]])

In [36]:
M - N

array([[ -7,   4,   1,   1],
       [-17,  14,  -7,   5],
       [ -2,  12,  -8,  -4],
       [  9,   7,  16,  12]])

In [37]:
M * N

array([[ 44,  77, 240,   2],
       [  0,  32, 144,  36],
       [255, 133, 153,  32],
       [  0,   8,  36,  28]])

In [38]:
N[N == 0] = 1
M / N

array([[0.36363636, 1.57142857, 1.06666667, 2.        ],
       [0.        , 8.        , 0.5625    , 2.25      ],
       [0.88235294, 2.71428571, 0.52941176, 0.5       ],
       [9.        , 8.        , 9.        , 7.        ]])

In [39]:
M * 5

array([[20, 55, 80, 10],
       [ 0, 80, 45, 45],
       [75, 95, 45, 20],
       [45, 40, 90, 70]])