## Numpy Übungen

Importiere hier alle benötigten Python Packages
* Numpy (mit dem Aliasnamen **np**)

In [148]:
import numpy as np
import traceback # für später

gebe für alle importieren Pakages die verwendete Versionummer aus.

Dazu musst du herausfinden wie die Version eines Python Packages ausgelesen werden kann.

In [149]:
print(np.__version__)

2.2.6


* Erzeuge einen Vektor!!! mit der Länge 5 und den Werten 1,2,3,4,5

In [150]:
vec = np.array(range(1,6))
vec

array([1, 2, 3, 4, 5])

Erzeuge folgende Matrizen

* 3x3 mit den Werten 1-9
* 4x6 mit den Werten 10,20,30,....
* 3x7 mit Werten im Bereich von 10-20. Die einzelnen Werte zueinander sollen dabei den gleichen Abstand haben.

In [151]:
m3x3 = np.arange(1,10).reshape([3,3])
m3x3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [152]:
m4x6 = np.arange(10,241,10).reshape([4,6])
m4x6

array([[ 10,  20,  30,  40,  50,  60],
       [ 70,  80,  90, 100, 110, 120],
       [130, 140, 150, 160, 170, 180],
       [190, 200, 210, 220, 230, 240]])

In [153]:
m3x7 = np.linspace(10,20, 21).reshape([3,7])
m3x7

array([[10. , 10.5, 11. , 11.5, 12. , 12.5, 13. ],
       [13.5, 14. , 14.5, 15. , 15.5, 16. , 16.5],
       [17. , 17.5, 18. , 18.5, 19. , 19.5, 20. ]])

Erzeuge eine Matrix 'v' (5x5) welche mit Zufallszahlen befüllt ist.
Die Zufallszahlen sollen dabei "Normalverteilt" sein.
Suche dazu die passende Funktion in der **numpy** Dokumentation.

In [154]:
v = np.random.normal(size=25).reshape([5,5])
v

array([[-1.02594037, -0.56986396,  0.61918126,  0.44498795, -0.20496573],
       [-0.67099712,  0.65826542,  0.33083646, -0.37815437,  1.03054031],
       [-1.69505398,  0.39316262, -0.3910823 , -1.08751051,  1.71267643],
       [-0.09500396, -0.2532217 ,  1.39124652, -0.21019626, -0.29187187],
       [ 2.18099307,  0.34559341, -0.64864091, -0.40695445, -1.17757518]])

Erzeuge eine Matrix 'v' (3x4) welche mit Zufallszahlen befüllt ist.
Die Zufallszahlen sollen dabei "Gleichverteilt" sein im Bereich von 20-30 sein
Suche dazu die passende Funktion in der **numpy** Dokumentation.

In [155]:
v = np.random.uniform(low=20,high=30,size=12).reshape([3,4])
v

array([[29.34058507, 23.99427977, 29.51778751, 21.77029613],
       [28.91937288, 24.43446701, 24.6227701 , 20.57615942],
       [24.28981004, 27.13513455, 27.58056755, 27.22763518]])

Erzeuge eine Matrix 'v' (2x5) welche mit Integer-Zufallszahlen befüllt ist.
Die Zufallszahlen sollen dabei "Gleichverteilt" sein im Bereich von 0-255 und mit dem Datentyp '**uint8**' abgespeichert werden.
Suche dazu die passende Funktion in der **numpy** Dokumentation.


In [156]:
v = np.random.randint(low=0,high=255, size=(2,5), dtype="uint8")
v

array([[ 32, 165, 100, 168,  42],
       [222, 223, 174, 111, 220]], dtype=uint8)

Erzeuge eine Matrix (3x3) welche aus lauter Nullen besteht und eine 2. Matrix welche aus lauter Einsen besteht.

Verwende zum Erzeugen der Matrix die passende numpy Funktion.

In [157]:
m3x3z = np.zeros((3,3))
m3x3z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [158]:
m3x3o = np.ones((3,3))
m3x3o

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

Erzeuge eine Matrix (4,4) welche in der Hauptdiagonale lauter Einser besitzt, alle anderen Elemente sollen Null sein.<br>
Eine Matrix welche in der Hauptdiagonale nur Einser besitzt und ansonsten lauter Nullen wird auch als **Einheitsmatrix** bezeichnet.

Verwende zum Erzeugen der Matrix die passende numpy Funktion.

In [159]:
m4identity = np.identity(4)
m4identity

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

Erzeuge eine Matrix M (3x3) mit Integer Zufallszahlen im Bereich (10,20] und Einheitsmatrix E, ebenfalls 3x3.<br>
Multipliziere (Matrixmultiplikation) die Matrix M mit der Einheitsmatrix E.
Wie lautet das Ergebnis der Berechnung und wie unterscheidet sich das Erbebnis von der ursprünglichen Matrix M?
$$
X = M * E
$$

In [160]:
M = np.random.randint(10,20, size=(3,3))
E = np.identity(3)
X = M * E

# Alles ist 0 wo E 0 ist
X

array([[11.,  0.,  0.],
       [ 0., 16.,  0.],
       [ 0.,  0., 12.]])

## Übungen zum Indizieren und Teilbereichsoperator

Erzeuge eine Matrix M (4x4) mit den Zahlen 1...16 welche für die nachfolgenden Übungen verwendet werden soll.<br>
Erzeuge auch einen Vektor V mit der Länge 10 und den Zahlen 2,4,6,8,......

In [161]:
M = np.arange(1, 17).reshape((4,4))
V = np.arange(2,21,2)

- Selektiere das 1. Element des Vektors V
- Selektiere die ersten 3 Elemente des Vektors V
- Seletiere alle ungeraden Elemente des Vektors V
- Selektiere das erste, fünfte und letzte Element des Vektors V

In [162]:
V[0]

np.int64(2)

In [163]:
V[:3]

array([2, 4, 6])

In [164]:
V[V % 2 == 1]

array([], dtype=int64)

In [165]:
V[[0,4,-1]]

array([ 2, 10, 20])

- Selektiere die erste Zeile der Matrix M
- Selektiere die erste Spalte der Matrix M
- Selektiere die ersten 3 Zeilen der Matrix M
- Selektiere die ersten 3 Spalten der Matrix M
- Selektiere die letzte Spalte der Matrix M
- Selektiere aus den Zeilen 1 und 2, die Spalten 3 und 4. Damit ergibt  sich eine neue 4x4 Matrix

In [166]:
M[0,:]

array([1, 2, 3, 4])

In [167]:
M[:,0]

array([ 1,  5,  9, 13])

In [168]:
M[:3,:]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [169]:
M[:,:3]

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15]])

In [170]:
M[:,-1]

array([ 4,  8, 12, 16])

In [171]:
M[:2,2:4]

array([[3, 4],
       [7, 8]])

Erzeuge eine Matrix M (5x4) mit zufälligen Integerwerten 0-300 und dem Datentyp uint16<br>

- Maskiere alle Werte der Matrix M welche größer als 255 sind und sezte diese auf den Wert 255. Speichere das Ergebnis in einer neuen Matrix mit dem Datentyp **uint8**. Schaue in der Doku mach mit welchem Befehl sich der Datentyp ändern läßt.

- Gib alle Elemente der Matrix M aus deren Wert eine 'gerade' Zahl ist.


In [172]:
M = np.random.randint(low=0, high=300, dtype="uint16", size=(5,4))
M

array([[169,  76, 240, 278],
       [184,  99, 277, 272],
       [129,  69, 123,  33],
       [163,  75,  25,  57],
       [108, 242, 281, 136]], dtype=uint16)

In [173]:
M2 = M.copy()
M2[M2 > 255] = 255
M2 = M2.astype("uint8")
M2

array([[169,  76, 240, 255],
       [184,  99, 255, 255],
       [129,  69, 123,  33],
       [163,  75,  25,  57],
       [108, 242, 255, 136]], dtype=uint8)

In [174]:
M[M % 2 == 0]

array([ 76, 240, 278, 184, 272, 108, 242, 136], dtype=uint16)

Erzeuge ein 2.Dim Python-Array!!! mit den Werte 1,2,3,4 in der 1. Zeile und <br>
5,6,7,8 in der 2. Zeile. Wandle dieses Array in ein numpy Array (Matrix M) um und gib dessen Shape aus.

- Erzeuge aus der Matrix M eine neue Matrix M2 (8x2)
- Erzeuge aus der Matrix M einen Vektor V. Entsprechende Funktion aus der Dokumentation raussuchen und anwenden. Wie viele Elemente enthält der entstandene Vektor?

In [175]:
#arr = [[1,2,3,4], [5,6,7,8]]
arr = [[b for b in range(a*4+1, (a+1)*4+1)] for a in range(2)]
M = np.array(arr)
M.shape

(2, 4)

In [176]:
try:
    M2 = M.reshape((8,2)) # kann nicht funktionieren, da M.size 16 ist
except ValueError as e:
    print(traceback.format_exc())

Traceback (most recent call last):
  File "/tmp/ipykernel_13861/4234647282.py", line 2, in <module>
    M2 = M.reshape((8,2)) # kann nicht funktionieren, da M.size 16 ist
ValueError: cannot reshape array of size 8 into shape (8,2)



In [177]:
V = M.flatten()
V # Antwort: 8 Elemente

array([1, 2, 3, 4, 5, 6, 7, 8])

Erzeuge 2 Matrizen M, N . Beide sollen die Dimension 2x2 haben und mit zufälligen Integerwerten befüllt sein.

- Erzeuge eine neue Matrix X indem die beiden Matrizen M, N horizontal aneinandergefügt werden. Gib die Werte der Matrix X sowie die Shape aus
- Erzeuge eine neue Matrix X indem die beiden Matrizen M, N vertikal aneinandergefügt werden. Gib die Werte der Matrix X sowie die Shape aus

In [178]:
M,N = [np.random.randint(low=0, high=255,size=(2,2)) for _ in range(2)]

In [179]:
X = np.hstack((M,N))
print(X.shape)
X

(2, 4)


array([[233, 229, 128, 240],
       [ 17, 160, 232, 227]])

In [180]:
X = np.vstack((M,N))
print(X.shape)
X

(4, 2)


array([[233, 229],
       [ 17, 160],
       [128, 240],
       [232, 227]])

## Numerische und Statistik Operationen auf Numpy Arrays

Erzeuge 2 Matrizen M, N . Beide sollen die Dimension 4x4 haben und mit zufälligen Integerwerten(0...20) befüllt sein.

- Addiere die beiden Matrizen
- Subtrahiere die beiden Matrizen
- Multiplizieren die beiden Matrizen
- Dividiere die beiden Matrizen. Sollten in der 2. Matrix an bestimmten Stellen nullen vorkommen, so sind diese vor der Divison durch eine 1 zu ersetzen (wegen Division durch 0)

- Multipliziere die Matrix M mit dem Skalarwert 5


In [181]:
M,N = [np.random.randint(low=0, high=20,size=(4,4)) for _ in range(2)]

In [182]:
M + N

array([[23, 25,  9, 16],
       [27, 33, 28,  6],
       [13, 20, 21, 18],
       [ 8,  6, 18,  1]])

In [183]:
M - N

array([[ -7,   9,  -7,  14],
       [  9,   3,   4,   0],
       [ 11,   2, -15, -14],
       [  8,  -4, -16,   1]])

In [184]:
M * N

array([[120, 136,   8,  15],
       [162, 270, 192,   9],
       [ 12,  99,  54,  32],
       [  0,   5,  17,   0]])

In [185]:
N[N == 0] = 1
M / N

array([[ 0.53333333,  2.125     ,  0.125     , 15.        ],
       [ 2.        ,  1.2       ,  1.33333333,  1.        ],
       [12.        ,  1.22222222,  0.16666667,  0.125     ],
       [ 8.        ,  0.2       ,  0.05882353,  1.        ]])

In [186]:
M * 5

array([[40, 85,  5, 75],
       [90, 90, 80, 15],
       [60, 55, 15, 10],
       [40,  5,  5,  5]])